# .github/workflows/4-copilot-comment.yml
name: Step 4, Add Copilot suggestion from comment
on:
  push:
    branches: [ main ]
jobs:
  check-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check workflow contents, jobs
        env:
          FILE: comments.js
          SEARCH: Create web server
        run: |
          echo "Check that all required env variables are set"
          if [ -z "$FILE" ]; then
            echo "FILE is unset or set to the empty string"
            exit 1
          fi
          if [ -z "$SEARCH" ]; then
            echo "SEARCH is unset or set to the empty string"
            exit 1
          fi
          if ! grep -q "$SEARCH" "$FILE"; then
            echo "Missing $SEARCH in $FILE"
            echo "----------------"
            echo "$(cat $FILE)"
            exit 204  # We're sending a weird code so it looks different from other "failures"
          fi
